### ISSUE TITLE
Fatal Error: module map not found

### ISSUE THREAD

**Issue by rgbinnovation** [AmolGangadhare/flutter_barcode_scanner#17]
Hi,

Have cleaned, removed pods, pod install but cannot run the project after adding this plugin. Getting the following:

fatal error: module map file '/Users/rgb/Repositories/app_flutter/build/ios/Debug-iphonesimulator/flutter_barcode_scanner/flutter_barcode_scanner.modulemap' not found

Any ideas?

**Comment by AmolGangadhare** [comment]
I'm figuring out the possible ways to solve it.
It's better to replace the `existing iOS folder` with `iOS with Swift` as mentioned in the`documentation`. 
I think the error is due to the iOS is created with objective-c by default, so there might be some necessary actions needed to make the plugin work even after the project have the swift file.
Request you to please follow the documentation for iOS and do let me know if you face any issue.

**Comment by AmolGangadhare** [comment]
Closing this as seems to be resolved. Please don't hesitate to reopen it if you face this again.
