### ISSUE TITLE
If user doesn't give camera permission widget error

### ISSUE THREAD

**Issue by NTMS2017** [AmolGangadhare/flutter_barcode_scanner#23]
If user doesn't give camera permission and try to use next time and also doesn't give camera permission there is a widget error.

Any idea?

```
E/flutter (15578): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
E/flutter (15578): At this point the state of the widget's element tree is no longer stable.
E/flutter (15578): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.
E/flutter (15578): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3389:9)
E/flutter (15578): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3403:6)
```

**Comment by AmolGangadhare** [comment]
It doesn't seem to be a plugin issue. I did some research on this error, it mainly causes due to context, but I'm not able to relate this to the current implementation. Can you add some more logs? and if possible can you provide some code you tried. I did the steps you provided but I'm not able to reproduce this error.

**Comment by AmolGangadhare** [comment]
Closing this as no response from the user,

feel free to reopen this if the issue persists
