### ISSUE TITLE
Can't find activity

### ISSUE THREAD

**Issue by bobdeng** [AmolGangadhare/flutter_barcode_scanner#4]
On android, show error:
E/FlutterBarcodeScannerPlugin(19340): startView: Unable to find explicit activity class {anguo.com.smartlockflutter/com.amolg.flutterbarcodescanner.BarcodeCaptureActivity}; have you declared this activity in your AndroidManifest.xml?
I/flutter (19340): 

It looks like the Activity not found.

**Comment by AmolGangadhare** [comment]
can you provide the steps you followed? had you clone it or using it from the pub?

**Comment by Baileypollard** [comment]
Also having this issue, any luck solving it?

**Comment by AmolGangadhare** [comment]
@Baileypollard sorry for the late reply. Have you faced this issue by cloning project from GitHub or by using it in pubspec?. Also, Invalidate cache and restart android studio once and try again.

**Comment by davidsonRG** [comment]
I am  having the same issue:

E/FlutterBarcodeScannerPlugin( 2276): startView: Unable to find explicit activity class {com.example.trash_talker/com.amolg.flutterbarcodescanner.BarcodeCaptureActivity}; have you declared this activity in your AndroidManifest.xml?

I added flutter_barcode_scanner: ^0.1.2+1 to my pubspec.yaml and then cut and pasted the code in your example. 

This happens when I click the Start Barcode Scan button on the device. The scan result text 'Unknown' clears and the error appears in the Debug Console.  I am using VS Code.

**Comment by davidsonRG** [comment]
Ok to fix this I had to do a flutter clean. After that I ran the project and it worked. Found the answer here: https://stackoverflow.com/questions/8107789/android-error-unable-to-find-explicit-activity-class

**Comment by AmolGangadhare** [comment]
@davidsonRG thanks for using the plugin. Unfortunately, you faced this issue, I'm thankful to you for trying and providing the solution here. It's a good idea to add FAQ in README section.

**Comment by AmolGangadhare** [comment]
It seems to be resolved, so closing this one. Please do not hesitate to reopen if the issue persists.
